# Site settings
title: Yeltzland - a dormant Halesowen Town website
email: johnp@bravelocation.com
twitter_username: yeltzland
github_username:  bravelocation
paginate: 10


# Build settings
markdown: kramdown
