# Site settings
title:              Yeltzland - a dormant Halesowen Town website
email:              johnp@bravelocation.com
twitter_username:   yeltzland
github_username:    bravelocation
url:                 http://www.yeltzland.net
baseurl:             ''
paginate: 10

# Build settings
markdown: kramdown

# Plugins
plugins: ['jekyll-paginate', 'jekyll-feed', 'jekyll-sitemap']

feed:
  path: rss.xml

# About/contact
author:
  name:              John Pollard
  url:               https://bravelocation.com/about
  email:             johnp@bravelocation.com
  twitter:           yeltzland
